import React from 'react';
import {AbsoluteFill, interpolate, spring, useCurrentFrame} from 'remotion';
import {Logo} from './design';
export const C={cream:'#f7f5f1',ink:'#111111',blue:'#3b82f6',green:'#34d399'};
export const clamp={extrapolateLeft:'clamp',extrapolateRight:'clamp'};
export const tween=(f,a,b,x,y)=>interpolate(f,[a,b],[x,y],clamp);
export const pop=(f,d=0)=>spring({frame:f-d,fps:30,config:{damping:18,stiffness:150,mass:.75}});
export function Stage({children,dark=false,blue=false}) {return <AbsoluteFill style={{background:blue?C.blue:dark?C.ink:C.cream,color:dark||blue?C.cream:C.ink,fontFamily:'Arial,Helvetica,sans-serif',overflow:'hidden'}}>{children}<div style={{position:'absolute',left:64,top:48,display:'flex',alignItems:'center',gap:12,fontSize:25,fontWeight:700}}><Logo size={34} dark={!dark&&!blue}/>RagKno</div><div style={{position:'absolute',right:64,bottom:42,fontSize:23,letterSpacing:-.5}}>ragkno.com</div></AbsoluteFill>}
export function Pointer({x,y,click=false}) {return <div style={{position:'absolute',left:x,top:y,zIndex:20,filter:'drop-shadow(0 4px 6px #0005)'}}>{click&&<div style={{position:'absolute',width:65,height:65,left:-32,top:-32,border:'3px solid #3b82f6',borderRadius:'50%'}}/>}<svg width="48" height="55" viewBox="0 0 36 42"><path d="M3 2L30 26L18 27L13 39Z" fill="#111" stroke="white" strokeWidth="3"/></svg></div>}
export function Paper({title='Quarterly report',type='PDF',accent=C.blue,style={}}){return <div style={{width:330,height:410,padding:32,background:'#fff',border:'1px solid #dfddd8',borderRadius:18,boxShadow:'0 24px 65px #0002',color:C.ink,...style}}><div style={{display:'flex',justifyContent:'space-between',fontSize:16,letterSpacing:2,color:'#777'}}><span>{type}</span><span>↗</span></div><div style={{height:5,width:42,background:accent,marginTop:35}}/><div style={{fontSize:33,lineHeight:1.1,fontWeight:700,marginTop:20}}>{title}</div><div style={{marginTop:35}}>{[100,83,92,65].map((w,i)=><div key={i} style={{height:7,width:`${w}%`,background:'#e9e7e2',marginTop:13,borderRadius:5}}/>)}</div><div style={{display:'flex',alignItems:'flex-end',gap:12,height:75,marginTop:30}}>{[32,52,40,72,60,85].map((h,i)=><div key={i} style={{height:`${h}%`,width:29,background:accent,opacity:.3+i*.12,borderRadius:'4px 4px 0 0'}}/>)}</div></div>}
export function Word({children,delay=0,style={}}){const f=useCurrentFrame();return <div style={{opacity:tween(f,delay,delay+8,0,1),translate:`0 ${(1-pop(f,delay))*95}px`,filter:`blur(${tween(f,delay,delay+12,10,0)}px)`,...style}}>{children}</div>}
